# Curio (python) motor controller node parameters

# Motor driver port settings
# port: /dev/cu.wchusbserialfd5110
port: /dev/ttyUSB1
baudrate: 115200
timeout: 1.0

# Update frequencies: control loop
control_frequency: 10.0

# Robot dimensions and limits
max_linear_speed: 1.0
max_linear_accel: 1.0

#  ROS frame convention for mobile robots:
# 
#                         x
#                         ^
#                         | longatudinal dir
#                         |
#  lateral dir  y <-------
# 
# 
# Wheel geometry / servo location. The numbers are servo serial ids:
# two digits for wheel servos, three digits for steering servos.
# 
#     <- front wheel lat separation ->
#    11 / 111 |-----|-----| 21 / 212   ---
#                   |                   ^
#                   |             front wheel lon separation
#       <- mid wheel lat separation ->  v
#        12 |-------|-------| 22       ---
#                   |                   ^
#                   |             back wheel lon separation
#                   |                   v
#   13 / 131 |------|------| 23 / 233  ---
#      <- back wheel lat separation ->
# 
wheel_width: 0.10
wheel_radius: 0.060
mid_wheel_lat_separation: 0.52
front_wheel_lat_separation: 0.47 
front_wheel_lon_separation: 0.28
back_wheel_lat_separation: 0.47
back_wheel_lon_separation: 0.25

# Steering servo configuration
#  - The offsets should be set so that a LX-16A servo command of 500
#    will set the corner wheels to face ahead (i.e. the wheel rotation
#    axis is parallel to the robot's y-axis using ROS base frame convetions)
steer_servo_offsets: [
    {   
        id: 111,
        offset: -10,
    },
    {   
        id: 121,
        offset: -5,
    },
    {   
        id: 211,
        offset: 40,
    },
    {   
        id: 231,
        offset: 20,
    }
]

